<script setup lang="ts">
import { formatNaira, formatNumber } from '~~/utils/format'
import type { PickupRequestView } from '../../../types'
definePageMeta({ layout: 'dashboard', middleware: 'auth' })
useSeoMeta({ title: 'Activity history — ReCircle', robots: 'noindex' })
const q = ref('')
const status = ref('')
const query = computed(() => ({ q: q.value || undefined, status: status.value || undefined }))
const { data, pending, refresh } = await useAsyncData('history', () => $fetch<{ items: Array<{ id: string; imageUrl: string; itemName: string | null; materialCode: string | null; status: string; weightKg: number | null; createdAt: string | null }>; requests: PickupRequestView[] }>('/api/history', { query: query.value }), { watch: [query] })
function itemLink(item: { id: string; status: string }) { return item.status === 'draft' || item.status === 'analyzed' ? `/scan/${item.id}/analysis` : `/scan/${item.id}/match` }
function onRequestUpdated() { void refresh() }
</script>
<template><div class="dash-page"><div class="dash-hero"><div><p class="eyebrow">Your activity</p><h1 class="page-title">Scan & pickup history.</h1><p class="muted workspace-intro">Find a previous item, check a pickup, or continue where you left off.</p></div></div><div class="history-filters"><input v-model="q" type="search" placeholder="Search item, material, or recycler"><select v-model="status"><option value="">All scan statuses</option><option value="draft">Draft</option><option value="analyzed">Analyzed</option><option value="matched">Matched</option><option value="pickup_requested">Pickup requested</option><option value="picked_up">Picked up</option><option value="completed">Completed</option></select><BaseButton size="sm" variant="ghost" @click="refresh">Refresh</BaseButton></div><LoadingSkeleton v-if="pending" :lines="6" label="Loading history" /><template v-else><DashboardSection title="Your scans" description="Recent items, from first photo to completed recycling."><div v-if="data?.items.length" class="history-list"><NuxtLink v-for="item in data.items" :key="item.id" :to="itemLink(item)"><img :src="item.imageUrl" :alt="item.itemName || 'Waste scan'"><div><strong>{{ item.itemName || item.materialCode || 'Draft item' }}</strong><span>{{ item.status.replaceAll('_', ' ') }}{{ item.weightKg != null ? ` · ${formatNumber(item.weightKg)} kg` : '' }}</span></div><time v-if="item.createdAt">{{ new Date(item.createdAt).toLocaleDateString('en-NG') }}</time></NuxtLink></div><EmptyState v-else compact title="No scans found" description="Try a different search or scan a new item." /></DashboardSection><DashboardSection title="Pickup requests" description="Every recycler request and its latest status."><div v-if="data?.requests.length" class="request-list"><RequestCard v-for="request in data.requests" :key="request.id" :request="request" role="user" @updated="onRequestUpdated" /></div><EmptyState v-else compact title="No pickup requests found" description="Pickup requests will appear here once you choose a recycler." /></DashboardSection></template></div></template>
